# Generated by Django 5.2.17 on 2026-09-29 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='الرمز')),
                ('module', models.SlugField(max_length=30, verbose_name='الوحدة')),
                ('label_ar', models.CharField(max_length=150, verbose_name='الوصف (عربي)')),
                ('description', models.TextField(blank=True, verbose_name='تفاصيل')),
            ],
            options={
                'verbose_name': 'صلاحية',
                'verbose_name_plural': 'الصلاحيات',
                'db_table': 'permissions',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم (EN)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_system', models.BooleanField(default=True, help_text='الدور المبني في النظام؛ لا يُحذف (يمكن تعديل صلاحياته).', verbose_name='دور نظام')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
                'db_table': 'roles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المنح')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_grants_made', to=settings.AUTH_USER_MODEL, verbose_name='مُعتمد بواسطة')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_to', to='accounts.permission', verbose_name='الصلاحية')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'صلاحية دور',
                'verbose_name_plural': 'صلاحيات الأدوار',
                'db_table': 'role_permissions',
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='uq_role_permission')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإسناد')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='مُسند بواسطة')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.role', verbose_name='الدور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إسناد دور',
                'verbose_name_plural': 'إسنادات الأدوار',
                'db_table': 'user_roles',
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='uq_user_role')],
            },
        ),
    ]
