# Generated by Django 5.2.17 on 2026-09-29 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, db_index=True, help_text='لقطة اسم المستخدم تبقى حتى لو حُذف الحساب.', max_length=150, verbose_name='اسم المنفّذ (لقطة)')),
                ('action', models.SlugField(choices=[('login', 'تسجيل دخول'), ('login_failed', 'محاولة دخول فاشلة'), ('logout', 'تسجيل خروج'), ('user_created', 'إنشاء مستخدم'), ('user_updated', 'تعديل مستخدم'), ('roles_changed', 'تغيير أدوار'), ('password_changed', 'تغيير كلمة مرور'), ('user_status_changed', 'تفعيل/تعطيل مستخدم')], verbose_name='العملية')),
                ('entity_type', models.SlugField(verbose_name='نوع الكيان')),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='معرّف الكيان')),
                ('diff', models.JSONField(blank=True, default=dict, help_text='الحقول المعدّلة مع قيمها السابقة والجديدة — بلا كلمات مرور أبدًا.', verbose_name='التغيير (قبل/بعد)')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='سياق')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='الوقت')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='ix_audit_entity_time')],
            },
        ),
    ]
