# Generated by Django 5.2.17 on 2026-09-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.SlugField(choices=[('login', 'تسجيل دخول'), ('login_failed', 'محاولة دخول فاشلة'), ('logout', 'تسجيل خروج'), ('user_created', 'إنشاء مستخدم'), ('user_updated', 'تعديل مستخدم'), ('roles_changed', 'تغيير أدوار'), ('password_changed', 'تغيير كلمة مرور'), ('user_status_changed', 'تفعيل/تعطيل مستخدم'), ('entity_created', 'إنشاء سجل مرجعي'), ('entity_updated', 'تعديل سجل مرجعي'), ('entity_deleted', 'حذف سجل مرجعي'), ('period_status_changed', 'فتح/إغلاق فترة شهرية'), ('closed_period_override', 'تسجيل في فترة مغلقة'), ('budget_approved', 'اعتماد نسخة ميزانية'), ('budget_unapproved', 'إلغاء اعتماد نسخة ميزانية'), ('budget_version_created', 'إنشاء نسخة ميزانية (مراجعة)'), ('expenses_exported', 'تصدير المصروفات (CSV)'), ('expense_attachment_viewed', 'عرض مستند مصروف مرفق'), ('procurement_attachment_viewed', 'عرض مستند مشتريات مرفق')], verbose_name='العملية'),
        ),
    ]
