# Generated by Django 5.2.17 on 2026-09-29 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0007_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.SlugField(choices=[('login', 'تسجيل دخول'), ('login_failed', 'محاولة دخول فاشلة'), ('logout', 'تسجيل خروج'), ('user_created', 'إنشاء مستخدم'), ('user_updated', 'تعديل مستخدم'), ('roles_changed', 'تغيير أدوار'), ('password_changed', 'تغيير كلمة مرور'), ('user_status_changed', 'تفعيل/تعطيل مستخدم'), ('entity_created', 'إنشاء سجل مرجعي'), ('entity_updated', 'تعديل سجل مرجعي'), ('entity_deleted', 'حذف سجل مرجعي'), ('period_status_changed', 'فتح/إغلاق فترة شهرية'), ('closed_period_override', 'تسجيل في فترة مغلقة'), ('budget_approved', 'اعتماد نسخة ميزانية'), ('budget_unapproved', 'إلغاء اعتماد نسخة ميزانية'), ('budget_version_created', 'إنشاء نسخة ميزانية (مراجعة)'), ('expenses_exported', 'تصدير المصروفات (CSV)'), ('expense_attachment_viewed', 'عرض مستند مصروف مرفق'), ('procurement_attachment_viewed', 'عرض مستند مشتريات مرفق'), ('data_imported', 'تنفيذ عملية استيراد'), ('import_file_downloaded', 'تنزيل ملف استيراد أصلي'), ('exception_evidence_viewed', 'عرض دليل استثناء رقابي'), ('attachment_uploaded', 'رفع مرفق'), ('attachment_viewed', 'عرض مرفق'), ('attachment_downloaded', 'تنزيل مرفق'), ('report_exported', 'تصدير تقرير')], verbose_name='العملية'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='الملف')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='العنوان')),
                ('entity_type', models.SlugField(choices=[('expense', 'مصروف'), ('procurement', 'مشتريات'), ('audit_exception', 'استثناء رقابي'), ('audit_finding', 'نتيجة رقابية')], max_length=30, verbose_name='نوع الكيان')),
                ('entity_id', models.CharField(db_index=True, max_length=60, verbose_name='معرّف الكيان')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت الرفع')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='الحجم (بايت)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الملف')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='رُفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'db_table': 'attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
