# Generated by Django 5.2.17 on 2026-09-29 14:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='الرمز')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='reference.department', verbose_name='الإدارة الأب')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'إدارة',
                'verbose_name_plural': 'الإدارات',
                'db_table': 'departments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='الرمز')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'تصنيف مصروفات',
                'verbose_name_plural': 'تصنيفات المصروفات',
                'db_table': 'expense_categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='رقم الحساب')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('asset', 'أصول'), ('liability', 'التزامات'), ('equity', 'حقوق ملكية'), ('income', 'إيرادات'), ('expense', 'مصروفات')], max_length=12, verbose_name='نوع الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='reference.account', verbose_name='الحساب الأب')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
                ('expense_category', models.ForeignKey(blank=True, help_text='يُربط فقط بحسابات نوع «مصروفات».', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='reference.expensecategory', verbose_name='تصنيف المصروف')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'دليل الحسابات',
                'db_table': 'accounts_chart',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='الرمز')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('year', models.PositiveSmallIntegerField(help_text='السنة التقويمية المقابلة، مثل 2026.', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='السنة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'سنة مالية',
                'verbose_name_plural': 'السنوات المالية',
                'db_table': 'fiscal_years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('month', models.PositiveSmallIntegerField(help_text='رقم الشهر التقويمي لبداية الفترة (1–12).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الشهر')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=10, verbose_name='الحالة (مفتوحة/مغلقة)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='reference.fiscalyear', verbose_name='السنة المالية')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'فترة شهرية',
                'verbose_name_plural': 'الفترات الشهرية',
                'db_table': 'monthly_periods',
                'ordering': ['fiscal_year__year', 'month'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='الرمز')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='اسم المورّد')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='مسؤول التواصل')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('tax_number', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='الرقم الضريبي')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'مورّد',
                'verbose_name_plural': 'الموردون',
                'db_table': 'suppliers',
                'ordering': ['code'],
            },
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='chk_fy_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='monthlyperiod',
            constraint=models.UniqueConstraint(fields=('fiscal_year', 'month'), name='uq_period_fy_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlyperiod',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='chk_period_start_before_end'),
        ),
    ]
