# Generated by Django 5.2.17 on 2026-10-06 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_seed_erp_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('code', models.SlugField(max_length=30, unique=True, verbose_name='رقم الموظف')),
                ('full_name', models.CharField(db_index=True, max_length=200, verbose_name='اسم الموظف')),
                ('cost_center', models.CharField(blank=True, max_length=100, verbose_name='مركز التكلفة')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='المسمى الوظيفي')),
                ('contract_type', models.CharField(choices=[('official', 'رسمي'), ('casual', 'يومي/عرضي'), ('temporary', 'مؤقت'), ('contractor', 'متعاقد')], default='official', max_length=20, verbose_name='نوع التعاقد')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العمل')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='reference.department', verbose_name='الإدارة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'db_table': 'employees',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['department', 'is_active'], name='emp_dept_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='employee_dates_valid')],
            },
        ),
    ]
