# Generated by Django 5.2.17 on 2026-10-06 13:16

import apps.reference.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currencies',
            field=models.JSONField(default=apps.reference.models.default_account_currencies, help_text='العملات المسموح بها للحساب، مثل YER وUSD وSAR.', verbose_name='العملات'),
        ),
        migrations.AddField(
            model_name='account',
            name='inclusion',
            field=models.CharField(blank=True, max_length=200, verbose_name='التضمين'),
        ),
        migrations.AddField(
            model_name='account',
            name='ledger_type',
            field=models.CharField(choices=[('main', 'رئيسي'), ('sub', 'فرعي')], default='main', max_length=8, verbose_name='النوع في الدليل'),
        ),
        migrations.AddField(
            model_name='account',
            name='level',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='المستوى'),
        ),
        migrations.AddField(
            model_name='account',
            name='report_type',
            field=models.CharField(blank=True, choices=[('balance_sheet', 'الميزانية العمومية'), ('profit_loss', 'أرباح وخسائر')], max_length=20, verbose_name='نوع التقرير'),
        ),
    ]
