# Generated by Django 5.2.17 on 2026-09-29 16:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, db_index=True, help_text='يُولَّد تلقائيًا (PR-سنة-تسلسل) إن تُرك فارغًا.', max_length=30, unique=True, verbose_name='رقم السجل')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.TextField(verbose_name='الوصف / الموضوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'بانتظار الاعتماد'), ('approved', 'معتمد'), ('ordered', 'أمر شراء صادر'), ('received', 'مستلَم'), ('cancelled', 'ملغى')], default='draft', max_length=12, verbose_name='حالة المشتريات')),
                ('purchase_order', models.CharField(blank=True, help_text='اتركه فارغًا لاختبار «غياب PO».', max_length=40, verbose_name='رقم أمر الشراء (PO)')),
                ('approval_reference', models.CharField(blank=True, max_length=80, verbose_name='مرجع الاعتماد')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدًا'), ('transfer', 'تحويل بنكي'), ('check', 'شيك'), ('credit', 'آجل')], default='transfer', max_length=10, verbose_name='طريقة الدفع')),
                ('payment_reference', models.CharField(blank=True, max_length=80, verbose_name='مرجع الدفع')),
                ('attachment', models.FileField(blank=True, help_text='مستند الترسية/العرض — بحد أقصى 10 ميجابايت.', upload_to='procurements/%Y/%m/', verbose_name='مستند مرفق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='reference.account', verbose_name='الحساب')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتُمد بواسطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='reference.department', verbose_name='الإدارة')),
                ('expense_category', models.ForeignKey(blank=True, help_text='يُورَد تلقائيًا من الحساب إن تُرك فارغًا.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='reference.expensecategory', verbose_name='تصنيف المصروف')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='reference.supplier', verbose_name='المورّد (الفائز/المرشَّح)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'سجل مشتريات',
                'verbose_name_plural': 'سجلات المشتريات',
                'db_table': 'procurements',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='قيمة العرض')),
                ('offer_date', models.DateField(blank=True, null=True, verbose_name='تاريخ العرض')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='رقم/مرجع العرض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='procurement.procurement', verbose_name='سجل المشتريات')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='reference.supplier', verbose_name='المورّد')),
            ],
            options={
                'verbose_name': 'عرض مورّد',
                'verbose_name_plural': 'عروض الموردين',
                'db_table': 'procurement_quotations',
                'ordering': ['amount'],
            },
        ),
        migrations.AddConstraint(
            model_name='procurement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_procurement_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('procurement', 'supplier'), name='uq_quote_per_supplier'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_quote_amount_positive'),
        ),
    ]
