# Generated by Django 5.2.17 on 2026-10-06 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('reference', '0005_account_currencies_account_inclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='analytical_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytical_procurements', to='reference.account', verbose_name='الحساب التحليلي'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='reference.account', verbose_name='الحساب الرئيسي'),
        ),
    ]
