# Generated by Django 5.2.17 on 2026-09-29 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='رقم التشغيل')),
                ('mode', models.CharField(choices=[('single', 'اختبار واحد'), ('selected', 'اختبارات محددة'), ('all_active', 'كل الاختبارات المفعّلة')], default='all_active', max_length=12, verbose_name='النمط')),
                ('status', models.CharField(choices=[('running', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل')], db_index=True, default='running', max_length=12, verbose_name='الحالة')),
                ('tests_total', models.PositiveSmallIntegerField(default=0)),
                ('tests_pass', models.PositiveSmallIntegerField(default=0, verbose_name='ناجح (pass)')),
                ('tests_flagged', models.PositiveSmallIntegerField(default=0, verbose_name='مُعلَّم (flagged)')),
                ('tests_fail', models.PositiveSmallIntegerField(default=0, verbose_name='فشل (fail)')),
                ('exceptions_total', models.PositiveIntegerField(default=0, verbose_name='إجمالي الاستثناءات')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_runs', to=settings.AUTH_USER_MODEL, verbose_name='نفّذه')),
            ],
            options={
                'verbose_name': 'تشغيل اختبارات',
                'verbose_name_plural': 'تشغيلات الاختبارات',
                'db_table': 'audit_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(help_text='مثال: T-EXP-03 — معرّف فريد للاختبار.', max_length=20, unique=True, verbose_name='Test ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('domain', models.CharField(choices=[('budget', 'الموازنة'), ('procurement', 'المشتريات'), ('expense', 'المصروفات'), ('general', 'عام')], default='general', max_length=20, verbose_name='النطاق')),
                ('objective', models.TextField(verbose_name='Objective — الهدف')),
                ('rule_text', models.TextField(verbose_name='Rule — القاعدة')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parameters — المعاملات (DB-managed)')),
                ('data_source', models.CharField(max_length=255, verbose_name='Data Source')),
                ('expected_result', models.TextField(verbose_name='Expected Result')),
                ('exception_type', models.CharField(help_text='نوع الاستثناء الافتراضي (قد يصدر المنفّذ أنواعًا فرعية).', max_length=200, verbose_name='Exception Type')),
                ('default_risk', models.CharField(choices=[('Low', 'منخفض'), ('Medium', 'متوسط'), ('High', 'مرتفع')], default='Medium', max_length=6, verbose_name='Default Risk')),
                ('auditor_action', models.TextField(verbose_name='Auditor Action — إجراء المدقّق')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active/Inactive — مفعّل')),
                ('engine_key', models.CharField(help_text='مفتاح المنفّذ المسجّل في الـ engine — يسمح بإنشاء اختبارات متعددة بنفس المنطق بمعاملات مختلفة.', max_length=60, verbose_name='محرّك التنفيذ')),
                ('synthetic_rule', models.BooleanField(default=True, help_text='افتراض تدريبي — ليست سياسة معتمدة من جهة حقيقية.', verbose_name='قاعدة تدريبية (Synthetic/Training Rule)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audit_tests', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_audit_tests', to=settings.AUTH_USER_MODEL, verbose_name='عدّل بواسطة')),
            ],
            options={
                'verbose_name': 'اختبار رقابي',
                'verbose_name_plural': 'الاختبارات الرقابية',
                'db_table': 'audit_tests',
                'ordering': ['test_code'],
            },
        ),
        migrations.CreateModel(
            name='AuditTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pass', 'ناجح (pass)'), ('flagged', 'مُعلَّم (flagged)'), ('fail', 'فشل (fail)')], db_index=True, max_length=10, verbose_name='النتيجة')),
                ('records_checked', models.PositiveIntegerField(default=0, verbose_name='سجلات مفحوصة')),
                ('exceptions_count', models.PositiveIntegerField(default=0, verbose_name='عدد الاستثناءات')),
                ('explanation', models.TextField(blank=True, verbose_name='لماذا هذه النتيجة — تفسير للمدقّق')),
                ('params_snapshot', models.JSONField(blank=True, default=dict, verbose_name='لقطة المعاملات وقت التشغيل (تتبّع)')),
                ('error', models.TextField(blank=True, verbose_name='خطأ التنفيذ')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='audit_register.auditrun')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='audit_register.audittest')),
            ],
            options={
                'verbose_name': 'نتيجة اختبار',
                'verbose_name_plural': 'نتائج الاختبارات',
                'db_table': 'audit_test_results',
                'ordering': ['test__test_code'],
            },
        ),
        migrations.CreateModel(
            name='AuditException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=20, verbose_name='لقطة Test ID')),
                ('source_type', models.CharField(help_text='expense / procurement / budget_combination …', max_length=40, verbose_name='نوع المصدر')),
                ('source_id', models.CharField(max_length=64, verbose_name='معرّف المصدر')),
                ('source_ref', models.JSONField(blank=True, default=dict, verbose_name='مرجع إضافي للتتبّع (إدارات/حسابات/فترات)')),
                ('exception_type', models.CharField(max_length=100, verbose_name='Exception Type')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مختصر')),
                ('explanation', models.TextField(verbose_name='لماذا سُجِّل — قيم فعلية مقابل عتبات الاختبار')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المبلغ')),
                ('currency', models.CharField(blank=True, max_length=3, verbose_name='العملة')),
                ('control_severity', models.CharField(choices=[('S1', 'S1 — مؤشر ملين'), ('S2', 'S2 — رقابي مؤكد'), ('S3', 'S3 — مباشر')], default='S2', max_length=2, verbose_name='شدة الخلل')),
                ('risk_level', models.CharField(choices=[('High', 'مرتفع'), ('Medium', 'متوسط'), ('Low', 'منخفض')], default='Medium', max_length=6, verbose_name='مستوى الخطر')),
                ('risk_rule_ref', models.CharField(blank=True, max_length=6, verbose_name='مرجع قاعدة الخطر')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('acknowledged', 'قيد الدراسة'), ('resolved', 'مُعالج')], db_index=True, default='open', max_length=12, verbose_name='الحالة')),
                ('status_note', models.TextField(blank=True, verbose_name='ملاحظة المعالجة')),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_audit_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='عالجه')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='audit_register.auditrun')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='audit_register.audittest')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='audit_register.audittestresult')),
            ],
            options={
                'verbose_name': 'استثناء رقابي',
                'verbose_name_plural': 'سجل الاستثناءات',
                'db_table': 'audit_exceptions',
                'ordering': ['status', '-risk_level', '-amount', 'test_code', 'source_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='audittestresult',
            constraint=models.UniqueConstraint(fields=('run', 'test'), name='uq_run_test_result'),
        ),
        migrations.AddIndex(
            model_name='auditexception',
            index=models.Index(fields=['run', 'status'], name='ix_aexc_run_status'),
        ),
        migrations.AddIndex(
            model_name='auditexception',
            index=models.Index(fields=['risk_level'], name='ix_aexc_risk'),
        ),
    ]
