# Generated by Django 5.2.17 on 2026-09-29 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_register', '0002_seed_audit_tests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditexception',
            name='auditor_action',
            field=models.TextField(blank=True, verbose_name='Auditor Action — إجراء المدقّق (لقطة من الاختبار وقت الاكتشاف)'),
        ),
        migrations.AddField(
            model_name='auditexception',
            name='evidence',
            field=models.FileField(blank=True, upload_to='evidence/%Y/%m/', verbose_name='Evidence — دليل مرفق'),
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='رقم النتيجة')),
                ('title', models.CharField(max_length=255, verbose_name='Finding — النتيجة')),
                ('criteria', models.TextField(help_text='السياسة/المعيار الذي خُالف (مرجع القاعدة).', verbose_name='Criteria — المعيار')),
                ('condition', models.TextField(help_text='الحالة الواقعية المثبتة بالأدلة.', verbose_name='Condition — الوضع الفعلي')),
                ('impact', models.TextField(help_text='الأثر الرقابي/المالي المقدر — وصف نوعي بلا نسب مخترعة.', verbose_name='Impact — الأثر')),
                ('cause', models.TextField(blank=True, help_text='يُملأ ONLY عند توفر دليل مباشر يدعمه — وإلا يُترك فارغًا.', verbose_name='Cause — السبب')),
                ('cause_supported', models.BooleanField(default=False, verbose_name='السبب مدعوم بدليل')),
                ('risk_level', models.CharField(choices=[('High', 'مرتفع'), ('Medium', 'متوسط'), ('Low', 'منخفض')], default='Medium', max_length=6, verbose_name='Risk Level')),
                ('recommendation', models.TextField(verbose_name='Recommendation — التوصية')),
                ('management_action', models.TextField(blank=True, verbose_name='Management Action — إجراء الإدارة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المعالجة'), ('closed', 'مُغلق')], db_index=True, default='open', max_length=15, verbose_name='Status')),
                ('status_note', models.TextField(blank=True, verbose_name='ملاحظة الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_findings', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('exceptions', models.ManyToManyField(related_name='linked_findings', to='audit_register.auditexception', verbose_name='الاستثناءات المرتبطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_findings', to=settings.AUTH_USER_MODEL, verbose_name='عدّل بواسطة')),
            ],
            options={
                'verbose_name': 'نتيجة رقابية (Finding)',
                'verbose_name_plural': 'النتائج والتوصيات',
                'db_table': 'audit_findings',
                'ordering': ['-created_at'],
            },
        ),
    ]
