# Generated by Django 5.2.17 on 2026-09-29 15:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(blank=True, db_index=True, help_text='يُولَّد تلقائيًا (EXP-سنة-تسلسل) إن تُرك فارغًا.', max_length=30, unique=True, verbose_name='رقم المصروف')),
                ('expense_date', models.DateField(verbose_name='تاريخ المصروف')),
                ('description', models.TextField(verbose_name='الوصف / البيان')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ')),
                ('currency', models.CharField(choices=[('USD', 'دولار أمريكي (USD)'), ('SAR', 'ريال سعودي (SAR)'), ('YER', 'ريال يمني (YER)')], default='USD', max_length=3, verbose_name='العملة')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدًا'), ('transfer', 'تحويل بنكي'), ('check', 'شيك'), ('other', 'أخرى')], default='transfer', max_length=10, verbose_name='طريقة الدفع')),
                ('payment_reference', models.CharField(blank=True, max_length=80, verbose_name='مرجع الدفع (تحويل/شيك)')),
                ('invoice_reference', models.CharField(blank=True, help_text='مرجع المستند — مع المورّد يُشكّل تحكمًا ضد التكرار.', max_length=80, null=True, verbose_name='رقم الفاتورة/المرجع')),
                ('attachment', models.FileField(blank=True, help_text='صورة/PDF للمستند — بحد أقصى 10 ميجابايت.', upload_to='expenses/%Y/%m/', verbose_name='مستند مرفق')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('approval_reference', models.CharField(blank=True, max_length=80, verbose_name='مرجع الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='reference.account', verbose_name='الحساب')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتُمد بواسطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='reference.department', verbose_name='الإدارة')),
                ('expense_category', models.ForeignKey(blank=True, help_text='يُورَد تلقائيًا من الحساب إن تُرك فارغًا.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='reference.expensecategory', verbose_name='تصنيف المصروف')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='reference.monthlyperiod', verbose_name='الفترة المحاسبية')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='reference.supplier', verbose_name='المورّد')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'مصروف فعلي',
                'verbose_name_plural': 'المصروفات الفعلية',
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_expense_amount_positive'), models.UniqueConstraint(condition=models.Q(('invoice_reference__isnull', False), models.Q(('invoice_reference', ''), _negated=True)), fields=('supplier', 'invoice_reference'), name='uq_expense_supplier_invoice')],
            },
        ),
    ]
