# Generated by Django 5.2.17 on 2026-09-29 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('expenses', 'المصروفات الفعلية')], default='expenses', max_length=30, verbose_name='الهدف')),
                ('source_file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='الملف الأصلي (يُحفظ دائمًا)')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel (xlsx)'), ('pdf', 'PDF')], max_length=10, verbose_name='الصيغة')),
                ('status', models.CharField(choices=[('uploaded', 'مرفوع'), ('extracted', 'مُستخرج — بانتظار المطابقة'), ('validated', 'مُتحقق — بانتظار التأكيد'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغى')], db_index=True, default='uploaded', max_length=12, verbose_name='الحالة')),
                ('headers', models.JSONField(blank=True, default=list, verbose_name='أعمدة الملف')),
                ('rows', models.JSONField(blank=True, default=list, verbose_name='الصفوف (مصدر + مطابقة + تحقق)')),
                ('extraction_warnings', models.JSONField(blank=True, default=list, verbose_name='تحذيرات الاستخراج')),
                ('ocr_used', models.BooleanField(default=False, verbose_name='استُخدم OCR')),
                ('column_map', models.JSONField(blank=True, default=dict, verbose_name='مطابقة الأعمدة (حقل الهدف ← عمود الملف)')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='ملخص التحقق')),
                ('imported_count', models.PositiveIntegerField(default=0, verbose_name='عدد الصفوف المستوردة')),
                ('job_log', models.JSONField(blank=True, default=list, verbose_name='سجل خطوات Import Job')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'عملية استيراد',
                'verbose_name_plural': 'عمليات الاستيراد',
                'db_table': 'import_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ix_importjob_status_time')],
            },
        ),
    ]
