# Generated by Django 5.2.17 on 2026-10-02 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='source_sha256',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64, verbose_name='بصمة الملف SHA-256'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.UniqueConstraint(condition=models.Q(('source_sha256', ''), _negated=True), fields=('source_sha256',), name='uq_importjob_source_sha256'),
        ),
    ]
