# Generated by Django 5.2.17 on 2026-10-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importjob_source_sha256_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='target',
            field=models.CharField(choices=[('fiscal_years', 'السنوات المالية'), ('periods', 'الفترات الشهرية'), ('departments', 'الإدارات'), ('expense_categories', 'تصنيفات المصروفات'), ('accounts', 'الدليل المحاسبي'), ('suppliers', 'الموردون'), ('budget_lines', 'الموازنة التقديرية — السطور الشهرية'), ('expenses', 'المصروفات الفعلية'), ('procurements', 'سجلات المشتريات'), ('quotations', 'عروض أسعار الموردين')], default='expenses', max_length=30, verbose_name='الهدف'),
        ),
    ]
