# Generated by Django 5.2.17 on 2026-10-03 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_alter_importjob_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='target',
            field=models.CharField(choices=[('fiscal_years', 'السنوات المالية'), ('periods', 'الفترات الشهرية'), ('departments', 'الإدارات'), ('expense_categories', 'تصنيفات المصروفات'), ('accounts', 'الدليل المحاسبي'), ('suppliers', 'الموردون'), ('budget_lines', 'الموازنة التقديرية — السطور الشهرية'), ('detailed_budget', 'الموازنة التفصيلية الأولية (أوراق متعددة)'), ('expenses', 'المصروفات الفعلية'), ('procurements', 'سجلات المشتريات'), ('quotations', 'عروض أسعار الموردين')], default='expenses', max_length=30, verbose_name='الهدف'),
        ),
        migrations.CreateModel(
            name='DetailedBudgetSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الورقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب الورقة')),
                ('headers', models.JSONField(blank=True, default=list, verbose_name='أعمدة الورقة')),
                ('rows', models.JSONField(blank=True, default=list, verbose_name='صفوف الورقة')),
                ('sheet_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='إجمالي الورقة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_sheets', to='imports.importjob', verbose_name='عملية الاستيراد')),
            ],
            options={
                'verbose_name': 'ورقة موازنة تفصيلية',
                'verbose_name_plural': 'أوراق الموازنة التفصيلية',
                'db_table': 'imports_detailed_budget_sheets',
                'ordering': ['job', 'order'],
            },
        ),
    ]
