# Generated by Django 5.2.17 on 2026-10-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_alter_importjob_target_detailedbudgetsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedbudgetsheet',
            name='display_title',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='العنوان الظاهر (صف العنوان المدمج)'),
        ),
    ]
