# Generated by Django 5.2.17 on 2026-09-29 15:18

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الميزانية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('fiscal_year', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='budget', to='reference.fiscalyear', verbose_name='السنة المالية')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'ميزانية',
                'verbose_name_plural': 'الموازنة',
                'db_table': 'budgets',
                'ordering': ['-fiscal_year__year'],
            },
        ),
        migrations.CreateModel(
            name='BudgetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='رقم النسخة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمدة')], default='draft', max_length=10, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات النسخة')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_approvals', to=settings.AUTH_USER_MODEL, verbose_name='معتمد بواسطة')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='budget.budget', verbose_name='الميزانية')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'نسخة ميزانية',
                'verbose_name_plural': 'نسخ الموازنة',
                'db_table': 'budget_versions',
                'ordering': ['budget', '-version'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('m01', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='شهر 1')),
                ('m02', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='شهر 2')),
                ('m03', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='شهر 3')),
                ('m04', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='شهر 4')),
                ('m05', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='شهر 5')),
                ('m06', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='شهر 6')),
                ('m07', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='شهر 7')),
                ('m08', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='شهر 8')),
                ('m09', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='شهر 9')),
                ('m10', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='شهر 10')),
                ('m11', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='شهر 11')),
                ('m12', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='شهر 12')),
                ('annual_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='الميزانية السنوية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات السطر')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='reference.account', verbose_name='الحساب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='reference.department', verbose_name='الإدارة')),
                ('expense_category', models.ForeignKey(blank=True, help_text='يُورَد تلقائيًا من الحساب إن تُرك فارغًا.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='reference.expensecategory', verbose_name='تصنيف المصروف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='budget.budgetversion', verbose_name='نسخة الميزانية')),
            ],
            options={
                'verbose_name': 'سطر ميزانية',
                'verbose_name_plural': 'سطور الموازنة',
                'db_table': 'budget_lines',
                'ordering': ['account__code', 'department__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='budgetversion',
            constraint=models.UniqueConstraint(fields=('budget', 'version'), name='uq_budget_version'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('version', 'department', 'account'), name='uq_budget_line'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('annual_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('m01'), '+', models.F('m02')), '+', models.F('m03')), '+', models.F('m04')), '+', models.F('m05')), '+', models.F('m06')), '+', models.F('m07')), '+', models.F('m08')), '+', models.F('m09')), '+', models.F('m10')), '+', models.F('m11')), '+', models.F('m12')))), name='chk_line_annual_is_monthly_sum'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('annual_amount__gte', 0)), name='chk_line_annual_non_negative'),
        ),
    ]
