# Generated by Django 5.2.17 on 2026-09-29 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetline',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budget.budgetversion', verbose_name='نسخة الميزانية'),
        ),
    ]
