# Generated by Django 5.2.17 on 2026-10-06 12:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budget_template_engine'),
        ('reference', '0004_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('name', models.CharField(max_length=180, verbose_name='اسم نموذج التخطيط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('review', 'قيد المراجعة'), ('approved', 'معتمد'), ('archived', 'مؤرشف')], default='draft', max_length=12, verbose_name='الحالة')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='رقم الإصدار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_plans', to='reference.currency', verbose_name='العملة')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_plans', to='reference.fiscalyear', verbose_name='السنة المالية')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'نموذج تخطيط موازنة',
                'verbose_name_plural': 'نماذج تخطيط الموازنة',
                'db_table': 'budget_plans',
                'ordering': ['-fiscal_year__year', 'name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('row_type', models.CharField(choices=[('title', 'عنوان'), ('main_account', 'حساب رئيسي'), ('analytical_account', 'حساب تحليلي'), ('detail', 'تفصيل'), ('subtotal', 'إجمالي فرعي'), ('total', 'إجمالي عام'), ('note', 'ملاحظة')], default='detail', max_length=24, verbose_name='نوع الصف')),
                ('display_name', models.CharField(max_length=220, verbose_name='اسم العرض')),
                ('unit_of_measure', models.CharField(blank=True, max_length=80, verbose_name='وحدة القياس')),
                ('input_mode', models.CharField(choices=[('none', 'بدون إدخال'), ('annual', 'مبلغ سنوي'), ('monthly', 'مبالغ شهرية'), ('quantity_price', 'كمية × سعر وحدة'), ('periodic', 'مبلغ دوري × عدد الفترات')], default='none', max_length=24, verbose_name='طريقة الإدخال')),
                ('distribution_method', models.CharField(choices=[('none', 'بدون توزيع'), ('equal', 'متساوٍ على 12 شهرًا'), ('manual', 'يدوي'), ('single_month', 'شهر واحد'), ('selected_months', 'أشهر مختارة')], default='none', max_length=24, verbose_name='طريقة التوزيع')),
                ('annual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ السنوي')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة')),
                ('periodic_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ الدوري')),
                ('periods_count', models.PositiveSmallIntegerField(default=0, verbose_name='عدد الفترات')),
                ('single_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='شهر الصرف')),
                ('selected_months', models.JSONField(blank=True, default=list, verbose_name='الأشهر المختارة')),
                ('estimation_basis', models.TextField(blank=True, verbose_name='أساس التقدير')),
                ('is_included', models.BooleanField(default=True, verbose_name='مضمّن في الإجماليات')),
                ('analytical_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_plan_analytical_lines', to='reference.account', verbose_name='الحساب التحليلي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_plan_lines', to='reference.department', verbose_name='الإدارة')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_plan_lines', to='reference.employee', verbose_name='الموظف')),
                ('main_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_plan_main_lines', to='reference.account', verbose_name='الحساب الرئيسي')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='budget.budgetplanline', verbose_name='البند الأب')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'بند نموذج موازنة',
                'verbose_name_plural': 'بنود نماذج الموازنة',
                'db_table': 'budget_plan_lines',
                'ordering': ['section__position', 'position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPlanPeriodAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الشهر')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_amounts', to='budget.budgetplanline', verbose_name='البند')),
            ],
            options={
                'verbose_name': 'مبلغ شهري لبند الموازنة',
                'verbose_name_plural': 'المبالغ الشهرية لبنود الموازنة',
                'db_table': 'budget_plan_period_amounts',
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPlanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('name', models.CharField(max_length=180, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('default_main_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_budget_plan_sections', to='reference.account', verbose_name='الحساب الرئيسي الافتراضي')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='budget.budgetplan', verbose_name='نموذج التخطيط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'قسم نموذج موازنة',
                'verbose_name_plural': 'أقسام نماذج الموازنة',
                'db_table': 'budget_plan_sections',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='budgetplanline',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budget.budgetplansection', verbose_name='القسم'),
        ),
        migrations.AddConstraint(
            model_name='budgetplan',
            constraint=models.UniqueConstraint(fields=('name', 'fiscal_year', 'version'), name='uq_budget_plan_name_year_version'),
        ),
        migrations.AddConstraint(
            model_name='budgetplanperiodamount',
            constraint=models.UniqueConstraint(fields=('line', 'month'), name='uq_budget_plan_line_month'),
        ),
        migrations.AddConstraint(
            model_name='budgetplanperiodamount',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='budget_plan_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='budgetplansection',
            constraint=models.UniqueConstraint(fields=('plan', 'position'), name='uq_budget_plan_section_position'),
        ),
        migrations.AddConstraint(
            model_name='budgetplanline',
            constraint=models.UniqueConstraint(fields=('section', 'position'), name='uq_budget_plan_line_position'),
        ),
    ]
