# Generated by Django 5.2.17 on 2026-10-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budgetplan_budgetplanline_budgetplanperiodamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetplanline',
            name='aggregate_sections',
            field=models.ManyToManyField(blank=True, help_text='يستخدم مع صفوف الإجمالي فقط، ولا يكرر المبالغ في المخرجات.', related_name='aggregate_lines', to='budget.budgetplansection', verbose_name='الأقسام الداخلة في الإجمالي'),
        ),
    ]
