# Generated by Django 5.2.17 on 2026-10-06 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_existing_sections_to_departments(apps, schema_editor):
    BudgetPlanSection = apps.get_model('budget', 'BudgetPlanSection')
    BudgetPlanLine = apps.get_model('budget', 'BudgetPlanLine')
    for section in BudgetPlanSection.objects.filter(department__isnull=True):
        department_ids = list(
            BudgetPlanLine.objects.filter(
                section_id=section.pk, department__isnull=False,
            ).values_list('department_id', flat=True).distinct()[:2]
        )
        if len(department_ids) != 1:
            continue
        department_id = department_ids[0]
        duplicate = BudgetPlanSection.objects.filter(
            plan_id=section.plan_id, department_id=department_id,
        ).exclude(pk=section.pk).exists()
        if not duplicate:
            section.department_id = department_id
            section.save(update_fields=['department'])


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_budgetplanline_aggregate_sections'),
        ('reference', '0005_account_currencies_account_inclusion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetplansection',
            name='department',
            field=models.ForeignKey(blank=True, help_text='يرتبط مباشرة بالهيكل التنظيمي في وحدة الإدارات.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_plan_sections', to='reference.department', verbose_name='الإدارة/القسم التنظيمي'),
        ),
        migrations.RunPython(
            link_existing_sections_to_departments,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='budgetplansection',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('plan', 'department'), name='uq_budget_plan_section_department'),
        ),
    ]
