# Generated by Django 5.2.17 on 2026-10-06 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_budgetplansection_department_and_more'),
        ('reference', '0005_account_currencies_account_inclusion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budgetline',
            name='uq_budget_line',
        ),
        migrations.AddField(
            model_name='budgetline',
            name='analytical_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytical_budget_lines', to='reference.account', verbose_name='الحساب التحليلي'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='reference.account', verbose_name='الحساب الرئيسي'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(condition=models.Q(('analytical_account__isnull', True)), fields=('version', 'department', 'account'), name='uq_budget_line_main_only'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(condition=models.Q(('analytical_account__isnull', False)), fields=('version', 'department', 'account', 'analytical_account'), name='uq_budget_line_with_analytical'),
        ),
    ]
